### PR TITLE
Document rate-limiting POST requests

### PR DESCRIPTION
**Pull request by jsejcksn**
From:

https://github.com/vasanthv/jsonbox/blob/6781bd24a2e292fe3ea2cd33c76a52d99f801b99/src/routes.js#L17-L18

### CODE REVIEW

**Comment by jsejcksn** [comment]
@vasanthv Just curious: Was this an arbitrary value or does it align with some quota calculation? I noticed it's reduced by 75% from the examples in `express-rate-limit`.

**Comment by vasanthv** [comment]
@jsejcksn Yes it's just an arbitrary number. I don't have any logic behind it. My main intention is that it should be around 1/minute.

**Comment by jsejcksn** [comment]
Thanks for sharing. I was wondering if you thought about situations where there are lots of devices behind a single IP (like a classroom), and that there will be short bursts of rapid activity for an hour or so during the class, but very little activity at other times in a 24-hour period.

**Comment by vasanthv** [comment]
I see your case, but jsonbox isn't for all use cases. They could use it as long they stick within limits for creating records. 
As you know, `read` & `update` isn't rate limited.

**Pull request merged**
