### PR TITLE
Add support for json-query syntax filtering

### PR DESCRIPTION
**Pull request by harlev**
Added an optional filtering using [json-query](https://github.com/auditassistant/json-query).
This should allow deep array filtering like the one requested in https://github.com/vasanthv/jsonbox/issues/30 . 

It is important to note (also mentioned in the readme) this is an optional extra filtering, and will not affect any of the existing behavior if not explicitly added by the user.  

Using the filter is by adding the `jq` url parameter. The supported syntax is detailed in the [json-query page](https://github.com/auditassistant/json-query)

### CODE REVIEW

**Comment by harlev** [comment]
There is an option of returning more types of data from such queries, like returning the actual parent of the items matching the filter. This will create a behavior more similar to the results returned by the current implementation.
@vasanthv I'm looking for your guidance of where you would like to take this

**Comment by vasanthv** [comment]
@harlev I actually liked this `json-query` implementation, but the thing that stops me from merging it is, users can give complex queries on a 1000 records and running more queries like that can hold the node.js thread. So I am in a dilemma. Please advise if I am wrong.

**Comment by harlev** [comment]
@vasanthv Yes. Technically it is possible to run a complex query in **all** the records in a box. I have no indication on how resource intensive this could be. Similar issue if running on just a few (or even just one) records, with a very long array inside it (limited by the size if record supported).

We could create some limit on the number of records at the point we apply the json-query. It may solve typical cases, but will not be a complete protection for abuse (is noted in example above).

**Comment by vasanthv** [comment]
@harlev the limit is already set to 1000 records per fetch.

**Comment by harlev** [comment]
@vasanthv my question was if we want to further limit the record number, only for the cases json-query is applied

**Comment by vasanthv** [comment]
@harlev 1000 seems ok to me. If someone abused then we can act to reduce the number? Any thoughts?

**Comment by harlev** [comment]
@vasanthv In this case, we should be able to merge this PR as is.

**Comment by vasanthv** [comment]
@harlev yes. will merge it shortly.

**Comment by vasanthv** [comment]
I am not convinced on this approach as this can change the output format. I would still want to maintain the output consistent. 
*Closing this now, as I am making new changes for version 2*

**Pull request closed without merging**
